# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy file
COPY . .

# Install dependency
RUN pip install --no-cache-dir -r requirements.txt

# Jalankan program
CMD ["python", "app.py"]
